name: Deploy

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}

          script: |
            cd ${{ secrets.SERVER_TEST_DEPLOY_DIR }}
            git checkout develop
            git fetch origin develop
            git pull origin develop
