name: Deploy

on:
  pull_request:
    branches:
      - develop
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}

          script: |
            if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              cd ${{ secrets.SERVER_PROD_DEPLOY_DIR }}
              git checkout main
              git fetch origin main
              git pull origin main
            elif [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
              cd ${{ secrets.SERVER_TEST_DEPLOY_DIR }}
              git checkout develop
              git fetch origin develop
              git pull origin develop
            fi
