name: Deploy For Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}

          script: |
            cd ${{ secrets.SERVER_TEST_DEPLOY_DIR }} || exit 1
            git checkout develop || exit 1
            git fetch origin develop || exit 1
            git pull origin develop || exit 1
